CREATE OR REPLACE TRIGGER EUREKA.TR_CLIENTE_GENERA_CODIGO
BEFORE INSERT ON EUREKA.CLIENTE
FOR EACH ROW
DECLARE
   V_ITEM NUMBER(10,0);
   V_LONG NUMBER(10,0);
   V_CODIGO VARCHAR(20);
BEGIN
   IF INSERTING AND :NEW.CHR_CLIECODIGO IS NULL THEN
      UPDATE EUREKA.CONTADOR
         SET int_contitem = int_contitem + 1
         WHERE UPPER(vch_conttabla) = 'CLIENTE'
         RETURNING int_contitem, int_contlongitud INTO V_ITEM, V_LONG;
      V_CODIGO := TO_CHAR(V_ITEM);
      V_CODIGO := LPAD(V_CODIGO,V_LONG,'0');
      :NEW.CHR_CLIECODIGO := V_CODIGO;
   END IF;
END TR_CLIENTE_GENERA_CODIGO;
/